import json,pathlib
N={}
def add(id,voice,melody,harmony,instruments,effects,style,check,rhythm=None):
 N[id]=dict(voice=voice,melody=melody,harmony=harmony,instruments=instruments,effects=effects,style=style,check=check,rhythm=rhythm or 'A fast regular pulse near 135 BPM is supported by two signal-analysis methods; 67–68 BPM is the corresponding half-time interpretation. Short syllables and repeated words carry the rhythmic interest. Use straight 4/4 as a reconstruction setting; the original meter and precise swing ratio are not verified.')
add('Dc1uBZahhts',
 'Male, energetic and slightly nasal according to the audio model; delivery lies between speaking, chanting, and singing. English-language diction is prominent. A specific regional accent and the number of layered takes are not established.',
 'The source text forms two short title calls, a question, an answer, a quick explanatory phrase and a final answer. The audio model describes narrow speech-like pitch movement rather than an elaborate tune. Suggested contour: keep the two title calls almost identical, let the question lift, and make the answer settle; give dry/sky longer phrase-ending vowels. Those directional choices are a recipe, not measured note intervals.',
 'Bright and playful in the model interpretation, with a compact repeating backing. The mixture does not support an unambiguous major/minor assignment. For generation, begin with a small cheerful tonal loop and let the voice dominate; avoid prescribing an unsupported chord progression.',
 'The model identifies a synthetic bass foundation, bright keyboard/synth-like sounds and punchy percussion. “Electronic novelty jingle” is better supported than a specific band lineup. An actual guitar, acoustic drum kit or named synthesizer is unverified.',
 'The model reports cartoon-like boing/bleep sounds in the final seconds and possible subtle vocal processing. These effect identities are tentative. A brief stutter before the last title call is compatible with repeated ASR readings of an extra pickup. Visual lightning does not establish an audible thunder effect.',
 'Very short playful electronic novelty jingle, about 135 BPM, straight driving pulse. Upfront energetic male English vocal, slightly nasal, precisely articulated rhythmic speech-singing. Two punchy Flaunching calls, a compact question and answer, then a quick rhyming line landing on dry and sky. Narrow repeating vocal motif, short bright synth accents, simple synthetic bass and crisp programmed percussion. Brief gap before the last title call. Suggested finish: one small cartoon bleep or boing and a clean stop. Aim for roughly 16 seconds, with very little intro.',
 'First compare the FLAWN-ching vowel, the little “a” pickup, the dry/sky phrase endings, and the spacing before the last hook. The audio-supported lyric is “soaping”; listen for whether it is an intentional pun or a different word.')
add('Dc8axxYIC3k',
 'High-energy male calls and chants, with forceful attacks and apparent grunted or percussive vocal sounds. The model interprets much of it as speech/shouting rather than sustained singing. The captioned guttae/good day pun is more reliable than the model’s literal “go” transcription.',
 'A tiny two-syllable motif is repeated and compressed into a rapid middle cluster. The important melodic identity is the recurring short inflection and vowel, not a long tune. Suggested rendition: a short lower pickup into a stronger AY syllable, then clipped repeats of that same cell. The exact source pitches and stress distribution are not established.',
 'Pitch content is too ambiguous for a reliable key. Treat this as a predominantly rhythmic vocal hook over a minimal tonal backing. A strong one- or two-chord loop is a proposed starting point, not a recovered progression.',
 'Electronic beat and low synthetic pulse are consistently reported. The vocal itself supplies much of the perceived rhythm; the model also hears boom-like vocalizations/grunts. No specific acoustic instruments are established.',
 'Stuttered/chopped repetitions and abrupt voice-like exclamations are central to the interpretation. The words versus grunts in the densest middle section remain uncertain. Keep effects short and rhythmically attached to the hook rather than adding a large cinematic transition.',
 'Playful male vocal chant over a minimal punchy electronic beat, about 135 BPM. A tiny two-syllable guh-tay hook is the main musical motif: spaced calls at first, a tight stuttering cluster in the middle, then the near-homophone good day as a comic spoken interruption. Clear consonants, energetic rounded vowels, short pitch inflections, little sustained melody. Synthetic low pulse and crisp percussion; brief percussive vocal grunts can support the rhythm. Return to spaced guttae calls after too many guttae. Around 22 seconds; compact and repetitive.',
 'Compare the two-syllable vowel pattern and the good-day pun before the backing. Match spaced versus chopped sections; the expanded repeat counts in the Suno version are provisional.')
add('DcRZB_PBFkr',
 'Clipped male chants/calls with apparent changes of pitch or vocal character. The model alternately describes unison/layered voices and contrasting male calls; the recording does not establish how many performers produced them.',
 'The short nouns form distinct rhythmic cells: quick two-syllable corbel repeats, longer bargeboard replies, then a succession of new word shapes. The model hears small rises and falls rather than extended lyrical melody. Suggested rendition: retain a narrow repeated-note chant, contrast the slower replies, and put a slightly broader accent on finial. No exact intervals are recovered.',
 'One excerpt model suggests a major-like sound, but its instrumental account conflicts with a later excerpt and the key profiles are close. Use a light repetitive tonal centre as a reconstruction choice, without treating G major or C minor as established.',
 'The final portion is described as an electronic beat and synthesized backing. The first portion is inconsistently described as nearly vocal-only, so backing prominence may be low or obscured by the voice. Use sparse synthetic low notes and short percussive accents as a conservative recipe; specific instrumental sources are unresolved.',
 'Abrupt emphasis, repeated vocal syllables and a short isolated final exclamation are supported by the transcript. Compression, doubling, and small room/reverb effects are model suggestions, not measured production settings. No named TV programme or original music source has been identified.',
 'Fast comic architectural catalogue chant, about 135 BPM. Upfront clearly articulated male English calls, clipped and rhythmic with small pitch inflections. Four quick corbel calls answered by two broader bargeboard calls. Give mullion, brace, quatrefoil, quoin, string course and buttress their own repeated rhythmic cells, then reprise the opening. Sparse punchy electronic percussion, simple synth bass, short bright accents; the words dominate the mix. Slight vocal layering is an optional texture. Finish with an isolated emphatic finial and a short tail, roughly 38 seconds overall.',
 'Compare the length ratio of corbel to bargeboard and the change of motif for every new term. Confirm the uncertain brace/quoin repeat counts; avoid accepting the ASR substitutions price or video.')
add('DcYTYvMBSMn',
 'Theatrical male rhythmic speech-singing, with tightly articulated list words and broader open-vowel exclamations. The model agrees on energetic chant-like delivery but disagrees on whether the percussion is instrumental or vocal.',
 'Each block contrasts rapid catalogue syllables with a sustained Ah and a longer technical name. This contrast is directly supported by the lyric timing and vocalized Ah detections. The model hears speech-like pitch changes and changing phrase contours. Suggested rendition: use one short recurring list motif, open the register and vowel for Ah, then resolve the longer name back into the next list. Exact pitch heights and intervals remain unverified.',
 'The strongest mixture profile is B-flat major, ahead of E-flat major, but this is still a heuristic result from a vocal-heavy clip. A bright major-like setting is a reasonable experiment; B-flat major can be tried as a test key, not stated as the original. No harmonic progression is recovered.',
 'At least a rhythmic low/percussive backing is indicated. One model excerpt hears drums, bass and synths; another hears beatboxing/sample-like percussion. Prefer a hybrid description—tight synthetic/vocal-like percussion and a low pulse—over claiming a live bass guitar or drum kit.',
 'Possible mild reverb or short delay on the voice. The final Palladio exclamation is followed by a sparse ending and a low percussive cue according to the short tail analysis. Specific delay times and effect devices are not known.',
 'Quirky theatrical male catalogue song, about 135 BPM, brisk straight rhythm. Precisely articulated short speech-sung lists contrast with broad sustained open-vowel Ah exclamations and elongated architectural names. Reuse the same compact motif for column, pilaster, fluted and capital sections. Light punchy electronic beat, low bass pulse, dry vocal-like percussion and sparse bright keyboard accents; keep the lead upfront. Try an E-flat-major-like pitch center with recurring B-flat-major color; leave exact chords and harmonic function flexible, since these are profile candidates rather than a score. Emphasise kuh-RIN-thee-un, eye-ON-ik and puh-LAH-dee-oh clearly. End with composite then Palladio and a short low percussive stop, roughly 54 seconds.',
 'Compare the clipped list sections with the sustained Ah passages. Preserve the syllable counts in pilaster, Corinthian, Ionic, composite and Palladio. Treat the B-flat key suggestion as optional.')
add('DcbYsWLhhdZ',
 'An emphatic male voice uses the same short door sound repeatedly, with spoken/shouted comic interruptions and changes of intensity. Accent labels from the audio model are not reliable enough to fix a regional accent.',
 'A one-word pitch-and-rhythm cell dominates, expanded with adjective pickups. Melodic movement is limited and largely follows speech intonation. Later Dumbledore lengthens the same door vowel into a punchline. Suggested rendition: retain one stable door motif, vary the preceding adjective, and save the largest lengthening and pause for the final pun; exact source notes are not established.',
 'The major/minor profile is essentially tied around C, so the original mode is unresolved. Use a repetitive low tonal loop and light comic mood as a starting point. Do not impose a long changing chord progression on the repeated one-word hook.',
 'Multiple excerpts describe a synthetic bass/melodic backing and programmed percussion. The final excerpt additionally hears bright 8-bit-like arpeggiation and chime-like accents; these are timbral descriptions rather than confirmed console hardware or synthesis methods.',
 'Abrupt comic interruptions and a long punchline passage are visible in the structure. The model reports cartoon-like noises, short chimes and whooshes in the later portion. The 24–28-second vocal/effect event is still not reliably decoded; the safe recreation choice is a brief break, explicitly differing from an exact transcription.',
 'Comic electronic door chant, about 135 BPM. Upfront male English voice, crisp spoken-sung one-word door hook with a long rounded vowel, repeated on a compact pitch cell. Change the adjective pickups while keeping the door motif stable. Try an F-minor-like opening, a C-centered middle around 18–28 seconds with minor/major color flexible, then a return toward F minor near the next door list; leave later harmony flexible. These are section-profile candidates, not verified chords. Simple synth bass and programmed drum groove, short bright keyboard stabs. Use dry spoken questions and answers, sudden small pauses, and a sharp cat flap interruption. Toward the end add a brief bright game-like arpeggio or chime texture, pause after and one more, then a drawn-out Dumbledore punchline and one final door. Roughly 65 seconds; no extra verses.',
 'Check the original repeated door count and the unresolved middle interjection. In generated audio, keep DAW consistent through Dumbledore and ensure the pause before the joke is retained.')
add('DcqWhZtBIEI',
 'Male rhythmic speech/singing with contrasting spoken characters or pitch registers. The model repeatedly hears theatrical call-and-response delivery; the deeper obviously aside contrasts with quicker lists. Actual performer count and regional accent are unresolved.',
 'The recurring two-syllable window phrase anchors the catalogue. Short noun lists alternate with question/answer exchanges, creating contour through speech rather than a continuous sung tune. Suggested contours: lift the casement question, settle the yes answer, and lower/flatten obviously. These are practical performance instructions; the source contour has not been transcribed note for note.',
 'The mixture gives G major and G minor as the leading candidates; that establishes neither one conclusively. The broad effect is energetic and comic. For a first generation use a simple repeating tonal backing; test G as a centre only if an explicit key is useful.',
 'Early/middle excerpts consistently suggest an electronic low line and bright synth backing. The last excerpt instead describes brass/woodwind-like stabs. It is safer to request short bright, slightly brassy synthetic accents than to claim a real brass or woodwind ensemble.',
 'Breathy inhalation/gasp-like sounds and abrupt dialogue interjections are reported in the middle. The final excerpt reports reverberant or broadcast-like texture, but its claims of tape hiss and provenance are not verified. Preserve short gaps and character changes; exact sampled sources and effect settings remain unknown.',
 'Playful theatrical window song, about 135 BPM, clear male English rhythmic speech-singing over a compact electronic groove. Try a G-minor-leaning center with a brief brighter G-major color around 32–38 seconds; exact chords remain unverified. A recurring WIN-doh hook anchors fast architectural lists. Alternate sung calls with dry comic dialogue: Casement, Is that a casement, Yes a casement; give Obviously a lower deadpan delivery and Very good a brief spoken reply. Tight programmed percussion, simple synth bass, bright short slightly brassy keyboard stabs. Narrow vocal motifs and speech-like pitch changes, occasional brief breath or gasp accents. End firmly with Open the window, Shut it again. Around 67 seconds; keep all dialogue audible.',
 'Compare the question/answer spacing, the lower obviously aside and the final commands. Confirm the short word after oriel before calling the transcript exact; avoid turning every line into a smooth sung chorus.')
add('DcvxvGDhSeb',
 'Male, energetic and slightly theatrical, with a chant-like speech-sung delivery. The model characterizes the performance as dominated by rhythm and articulation rather than separate sustained notes.',
 'Paired three-syllable names alternate with a short phrase and a longer answer ending in shaft. Repetition of “a gently swelling shaft” supplies the ending motif. Suggested rendition: make the technical terms springy and compact, then gently lengthen the final shaft vowel in each response. Actual pitch intervals and any terminal glide are not measured.',
 'C major is the leading mixed-audio profile, but C minor also scores meaningfully. Use a light repetitive tonal setting; C major is an optional trial key rather than a verified source key. The vocal rhythm is better established than the harmony.',
 'The model identifies synthetic drum, bass and keyboard-like textures. It does not identify an acoustic lead instrument with adequate support. Keep the backing sparse enough to retain all three syllables of each technical word.',
 'A short swoosh-like sound near the ending is reported by the model. Digital/clean overall texture is plausible, but the exact processor is unknown. The most important audible form is the spaced repetition of the final line, supported by both recognizer passes.',
 'Short quirky electronic chant, about 135 BPM. Clearly enunciated male English speech-singing, slightly theatrical. Pair the three-syllable motifs ih-KY-nus and EN-tuh-sis; answer with A bulbous end and A gently swelling shaft. Narrow rhythmic vocal contour, compact consonants and a longer final shaft vowel. Sparse synthetic bass, punchy programmed drums and light keyboard accents. Repeat the final descriptive phrase with small spaces between calls; optional short swoosh at the end. Suggested light major mood, roughly 22 seconds, no added verses.',
 'Check the actual vowels and stress of echinus and entasis against the source. Keep “end” audible as a noun and do not let the generator merge it into “and”.')
add('DdLxzBIoJ8F',
 'An upfront, relatively dry male voice with conversational, clearly enunciated rhythmic delivery. The model hears pitch bends and dramatic pauses; the lyric pattern includes separate comic asides.',
 'Hall house is the recurring two-word refrain, while the verse moves quickly through rhyming phrases. The source sequence supports repeated couplet-length units, changing to spoken asides on oh behave and very private. Suggested rendition: broaden the two stresses of HALL HOUSE, keep the descriptive lines on a narrow patter melody, and briefly drop the aside into speech. Exact notes and a sung range are not established.',
 'Whole-mixture key correlations are weak and nearly tied; no key or major/minor mode is established. Preserve a simple low tonal backing and the rhythmic phrasing rather than forcing a supposedly exact progression. The model’s mood descriptions range from lively/quirky to slightly dark, so the recreation can keep a playful deadpan tone without prescribing a dark minor mode.',
 'The model consistently describes an electronic beat and synthesized low line, with occasional higher chime-like accents. It also suggests sampler-like percussion, but specific 808 hardware and named game associations are unsupported and omitted from the recipe.',
 'Short whoosh-like transitions and chime-like accents are model-reported possibilities. The dry foreground voice, pauses, and comic asides are the more stable description. No identifiable original game, show, artist or sample source has been established.',
 'Deadpan comic architectural patter song, about 135 BPM. Upfront clearly articulated male English rhythmic speech-singing, dry and conversational with small pitch bends. A broad two-beat HALL HOUSE refrain returns between quick rhyming descriptive couplets. Minimal electronic drum groove, low synth pulse, sparse bright chime-like accents. Let Oh behave and Very private become isolated spoken asides with small pauses; keep cross passage, hearth and solar intelligible. Reprise Have you visited a hall house at the ending. Around 50 seconds, compact arrangement with no new chorus or extra verses.',
 'Compare the two strong hall-house syllables, the patter speed of the couplets, and the pauses around oh behave and very private. Check that hearth does not become earth and solar remains a two-syllable room name.')
pathlib.Path('suno_recreation/evidence/music_notes.json').write_text(json.dumps(N,indent=2))
